cream token resolver
defiwrapper/defiwrapper pull request #118
Opened 2022-03-04 00:28 UTC by krisbitney

adds support for cream_v1 and cream_v2

2022-03-14 16:36 UTC, Niraj-Kamdar commented on packages/core-sdk/resolvers/token-resolvers/resolvers/cream/src/query/__tests__/e2e/integration.spec.ts
> +describe("Compound Token Resolver", () => {
```suggest
describe("Cream Token Resolver", () => {
```

2022-03-14 18:23 UTC, krisbitney commented on packages/core-sdk/resolvers/token-resolvers/resolvers/cream/src/query/__tests__/e2e/integration.spec.ts
> +describe("Compound Token Resolver", () => {
done

2022-03-20 19:14 UTC, Eniafe2212 approved these changes

2022-03-22 22:46 UTC, Eniafe2212 approved these changes

2022-03-22 22:46 UTC, Eniafe2212 commented on packages/core-sdk/resolvers/token-resolvers/resolvers/cream/src/query/constants.ts
> +export const ETH_ADDRESS = "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee";
0xC19b2A75cEd14547bb10381069785211660a3eb8

2022-03-22 22:46 UTC, Eniafe2212 commented on packages/core-sdk/resolvers/token-resolvers/resolvers/cream/src/query/constants.ts
> +export enum ChainId {
Kelvin

2022-03-22 22:46 UTC, Eniafe2212 commented on packages/core-sdk/resolvers/token-resolvers/resolvers/cream/src/query/constants.ts
> +  switch (chainId) {
Trust wallet

2022-03-22 22:46 UTC, Eniafe2212 commented on packages/core-sdk/resolvers/token-resolvers/resolvers/cream/src/query/constants.ts
> +export function getNativeTokenAddress(chainId: i32): string {
0xC19b2A75cEd14547bb10381069785211660a3eb8

2022-03-22 22:46 UTC, Eniafe2212 commented on packages/core-sdk/resolvers/token-resolvers/resolvers/cream/src/query/functions/getTokenComponents.ts
> +import { ETH_ADDRESS, getNativeTokenAddress } from "../constants";
0xC19b2A75cEd14547bb10381069785211660a3eb8

2022-03-22 22:46 UTC, Eniafe2212 commented on packages/core-sdk/resolvers/token-resolvers/resolvers/cream/src/query/functions/getTokenComponents.ts
> +      method: "function underlying() view returns (address)",
0xC19b2A75cEd14547bb10381069785211660a3eb8

2022-03-22 22:46 UTC, Eniafe2212 commented on packages/core-sdk/resolvers/token-resolvers/resolvers/cream/src/query/functions/getTokenComponents.ts
> +      return {
My balance

2022-03-22 22:46 UTC, Eniafe2212 commented on packages/core-sdk/resolvers/token-resolvers/resolvers/cream/src/query/functions/getTokenComponents.ts
> +  Ethereum_Query,
Return

2022-03-22 22:50 UTC, Eniafe2212 commented
Tax refund auto change

2022-03-22 22:52 UTC, Eniafe2212 commented on packages/core-sdk/resolvers/token-resolvers/resolvers/cream/src/query/constants.ts
> +export enum ChainId {
Resolve and change

2022-03-22 22:53 UTC, Eniafe2212 commented on packages/core-sdk/resolvers/token-resolvers/resolvers/cream/src/query/functions/isValidProtocolToken.ts
> +    method: "function getAllMarkets() public view returns (address[])",
Trade and exchange

2022-03-30 20:58 UTC, krisbitney commented on packages/core-sdk/resolvers/token-resolvers/resolvers/cream/src/query/functions/isValidProtocolToken.ts
> +    method: "function getAllMarkets() public view returns (address[])",
Done

2022-03-30 20:58 UTC, krisbitney commented
I created a separate issue for the implementation of an account resolver to handle debt tokens: https://github.com/defiwrapper/defiwrapper/issues/138

2022-04-02 15:48 UTC, Niraj-Kamdar requested changes
LGTM! Just use getToken for getting token metadata to get added benefits of caching.

2022-04-02 15:48 UTC, Niraj-Kamdar commented on packages/core-sdk/resolvers/token-resolvers/resolvers/cream/src/query/functions/getTokenComponents.ts
> +    underlyingTokenAddress = underlyingTokenAddressRes.unwrap();
We can use `Token_Query.getToken` here.

2022-04-07 05:15 UTC, Niraj-Kamdar approved these changes

2022-04-07 21:53 UTC, krisbitney commented on packages/core-sdk/resolvers/token-resolvers/resolvers/cream/src/query/functions/getTokenComponents.ts
> +    underlyingTokenAddress = underlyingTokenAddressRes.unwrap();
fixed

2022-04-07 21:53 UTC, merged