feat(defi-sdk/token-resolver): update to origin
defiwrapper/defiwrapper pull request #176
Opened 2022-08-09 14:15 UTC by cbrzn

2022-08-09 14:16 UTC, cbrzn commented
closes #175

2022-08-10 14:06 UTC, Niraj-Kamdar requested changes

2022-08-10 14:06 UTC, Niraj-Kamdar commented on packages/defi-sdk/resolvers/token-resolvers/resolvers/ethereum/src/schema.graphql
> +}
Remove Env from here since not needed. ethereum plugin support env now and we can configure the env for ethereum plugin from client now.

2022-08-11 18:23 UTC, cbrzn commented on packages/defi-sdk/resolvers/token-resolvers/interface/schema.graphql
> +  getToken(address: String!, type: String!): Token! @env(required: false)
I added it because we were using `QueryEnv` - My bad :P

2022-08-15 11:30 UTC, Niraj-Kamdar approved these changes

2022-08-15 18:58 UTC, merged